### ISSUE TITLE
Jobscribe link is broken

### ISSUE THREAD

**Issue by KirankumarAmbati** [Wakkos/RemoteJobs#6]
![screenshot_20180909-114755](https://user-images.githubusercontent.com/9110567/45261766-6de0b500-b426-11e8-8678-173c23d30960.png)

Jobscribe link is broken and googling about jobscribe gave me https://jobscribe.co.nz link. Can I correct it ? Please clarify.

**Comment by KirankumarAmbati** [comment]
CC: @Wakkos

**Comment by Wakkos** [comment]
Hello, if you want you can make a pull request!

**Comment by KirankumarAmbati** [comment]
Pull Request: #7

**Comment by KirankumarAmbati** [comment]
Addressed.
